apiVersion: v1
kind: PersistentVolume
metadata:
  name: tekton-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  local:
    path: /Users/nakumar/k8slocalvol
