apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-pv-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
